import 'package:equatable/equatable.dart';

import '../../../../core/domain/entities/geo_coordinate.dart';

enum ManeuverType { start, left, right, straight, arrive }

/// One line of turn-by-turn guidance (report Table 11 / requirement A8),
/// generated by walking a route's full geometry and flagging bearing
/// changes — see [RoutingEngine]. `straight` currently isn't emitted (only
/// turns and the start/arrive bookends are), but the type exists for when
/// Route Guide wants to render every leg rather than only the turns.
class GuidanceInstruction extends Equatable {
  const GuidanceInstruction({
    required this.stepOrder,
    required this.action,
    required this.text,
    required this.location,
    required this.legDistanceMeters,
  });

  final int stepOrder;
  final ManeuverType action;
  final String text;
  final GeoCoordinate location;

  /// Distance walked since the previous instruction.
  final double legDistanceMeters;

  @override
  List<Object?> get props => [stepOrder, action, text, location, legDistanceMeters];
}
